#!/bin/bash
#
# A hook script to verify what is about to be committed.
# Called by "git commit".  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

ex=0;

for FILE in `git diff --cached --name-only`; do
	if [ "`basename $FILE`" == "multiply.csv" ] && [ -e $FILE ]; then
		for WHAT in {Columns,Rows}; do
			grep -q "^Number of $WHAT (integer):$(echo -ne \\t)1$" "$FILE"
			if [ $? != 0 ]; then
				echo "Too many $WHAT in $FILE" 1>&2
				ex=1
			fi
		done
	fi
done

exit $ex
